### ISSUE TITLE
Copyright/License violation

### ISSUE THREAD

**Issue by V01D-NULL** [marfanr/sincroll#1]
Hey, I'm V01D, the developer of Validity OS.

It seems that most of your code is *inspired* by my kernel and portions are even copied with minor changes to variable names. 

My kernel is licensed under GPLv3 which demands that you credit the owner.
(You actually forgot to credit the GDT code which I borrowed from another kernel myself so that's two violations) 

Please get that fixed asap, otherwise I will have to issue a takedown request.

**Comment by marfanr** [comment]
I'm really sorry, I fixed it

**Comment by marfanr** [comment]
I've given a copyright in every file that I was inspired by your code
